server:
  port: 8082

spring:
  application.name: temperature-monitoring
  datasource:
    username: sa
    url: jdbc:h2:mem:temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    password: 123
  
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 5 #Define a quantidade de mensagens que irá receber por vez
        retry:
          enabled: true
          initial-interval: 10s #Tempo incremental até combar (intervalo maximo ou a quantidade de tentativas) (10 20 30 ....)
          max-interval: 30s
          multiplier: 2
          max-attempts: 3
          